# Generated by Django 3.2.6 on 2021-08-29 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Beer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('taste', models.CharField(max_length=200)),
                ('color', models.CharField(max_length=100)),
                ('price', models.FloatField()),
            ],
        ),
    ]
